import { Profile } from "./_team";

export const team2024: Profile[] = [
  {
    name: "Vijaya Mair",
    title: "Placement Co-ordinator and Mentor",
    src: "/img/team/vijaya_mair.jpg",
    linkedin: "https://www.linkedin.com/in/vijayamair/",
  },
  {
    name: "Seetharam Nagesh Appe",
    title: "Faculty Co-Ordinator",
    src: "/img/team/nagesh.jpeg",
    linkedin: "https://www.linkedin.com/in/seetharamnagesh-appe-4584281aa/",
  },
  {
    name: "Sheetal Gujar",
    title: "GDSC Lead",
    src: "/img/team/Sheetal Gujar.jpeg",
    instagram: "https://www.instagram.com/_shheetal/",
    github: "https://github.com/sshheetal",
    linkedin: "https://www.linkedin.com/in/sheetal-gujar/",
  },
  {
    name: "Vishal Keerthan Parankusham",
    title: "Web Core Team Lead",
    src: "/img/team/Vishal Keerthan.jpg",
    instagram: "https://www.instagram.com/pvishalkeerthan/",
    github: "https://github.com/pvishalkeerthan",
    linkedin: "https://www.linkedin.com/in/vishal-keerthan/",
  },
  {
    title: "Web Core Team Member",
    name: "Suraj Thammi",
    src: "/img/team/Suraj Thammi.png",
    instagram: "https://www.instagram.com/suraj__712",
    github: "https://github.com/suraj719",
    linkedin: "https://www.linkedin.com/in/surajthammi/",
  },
  {
    title: "Web Core Team Member",
    name: "Sneha Muthyala",
    src: "/img/team/Sneha Muthyala.jpg",
    github: "https://github.com/SnehaMuthyala",
    linkedin: "https://www.linkedin.com/in/sneha-muthyala-78594a280",
  },
  {
    title: "Web Core Team Member",
    name: "Siripuram Akash",
    src: "/img/team/Siripuram Akash.jpeg",
    instagram: "https://www.instagram.com/akash_siripuram_19",
    github: "https://github.com/akashsiripuram",
    linkedin: "https://www.linkedin.com/in/siripuramakash",
  },
  {
    title: "Android Core Team Lead",
    name: "Aryan Shivva",
    src: "/img/team/Aryan Shivva.jpg",
    instagram: "https://github.com/AryanShivva",
    github: "https://github.com/AryanShivva",
    linkedin: "https://www.linkedin.com/in/aryan-shivva-839669256/",
  },
  {
    title: "Android Core Team Member",
    name: "Pesarikayala Sai Charan Reddy",
    src: "/img/team/Sai Charan Reddy.jpeg",
    instagram: "https://www.instagram.com/saicharanreddy_79",
    github: "https://github.com/PSaiCharanReddy",
    linkedin:
      "https://www.linkedin.com/in/pesarikayalasaicharanreddypesarikayala/",
  },
  {
    title: "Android Core Team Member",
    name: "Anjith surya vamshi",
    src: "/img/team/Anjith surya vamshi.jpg",
    instagram: "https://www.instagram.com/anjith.sv",
    github: "https://github.com/AnjithSuryaVamshi",
    linkedin: "https://www.linkedin.com/in/anjith-a561a22a0/",
  },
  {
    title: "AI/ML & DS Core Team Lead",
    name: "K Shanthan",
    src: "/img/team/K Shanthan.jpg",
    instagram: "https://www.instagram.com/shanthan_katkuri",
    github: "https://www.github.com/shanthankatkuri",
    linkedin: "https://www.linkedin.com/in/shanthanreddykatkuri/",
  },
  {
    title: "AI/ML & DS Core Team Member",
    name: "Kruthin Reddy",
    src: "/img/team/Kruthin Reddy.jpeg",
    instagram: "https://www.instagram.com/kruthin_reddy",
    github: "https://github.com/Rikkykruthin",
    linkedin: "https://www.linkedin.com/in/kruthin-reddy",
  },
  {
    title: "AI/ML & DS Core Team Member",
    name: "K Rohith Kumar",
    src: "/img/team/K Rohith Kumar.jpeg",
    instagram: "https://www.instagram.com/umheyitsrohit",
    github: "https://github.com/rohitkumar9989",
    linkedin: "https://www.linkedin.com/in/rohith-kumar-650560215",
  },
  {
    title: "AI/ML & DS Core Team Member",
    name: "Badisa Srinidhi",
    src: "/img/team/Badisa Srinidhi.jpg",
    instagram: "https://www.instagram.com/bsrinidhi_04",
    github: "http://github.com/SNidhi2004",
    linkedin: "http://www.linkedin.com/in/srinidhi-badisa- 10311b301",
  },
  {
    title: "Cybersecurity & Block Chain Core Team Lead",
    name: "Rajaram Ramavath",
    src: "/img/team/Rajaram Ramavath.jpg",
    instagram: "https://www.instagram.com/id._.ram",
    github: "https://github.com/rajaramramavath",
    linkedin: "http://www.linkedin.com/in/rajaram-ramavath",
  },
  {
    title: "Cybersecurity & Block Chain Core Team Member",
    name: "Mani Venkata Sai Medam",
    src: "/img/team/Mani Venkata Sai Medam.jpg",
    instagram: "https://www.instagram.com/_m_m_v_s_",
    github: "https://github.com/manivenkatasai9494",
    linkedin: "https://www.linkedin.com/in/manivenkatasaimedam/",
  },
  {
    title: "Cybersecurity & Block Chain Core Team Member",
    name: "Shaik Saalam",
    src: "/img/team/Shaik Saalam.jpeg",
    instagram: "https://www.instagram.com/vr0nti",
    github: "https://github.com/Saalam121",
    linkedin: "https://www.linkedin.com/in/vronti/",
  },
  {
    title: "Cybersecurity & Block Chain Core Team Member",
    name: "Padigepati Sai Charan Reddy",
    src: "/img/team/Padigepati Sai Charan Reddy.jpg",
    instagram: "https://www.instagram.com/sai___charan__reddy",
    github: "https://github.com/SaicharanCEH",
    linkedin:
      "http://www.linkedin.com/in/sai-charan-reddy-padigepati-841658291",
  },
  {
    title: "Competitive Programming Core Team Lead",
    name: "Ananya Pappula",
    src: "/img/team/Ananya Pappula.jpg",
    instagram: "https://www.instagram.com/_ananya_521",
    github: "https://github.com/Ananya54321",
    linkedin: "https://www.linkedin.com/in/ananya-pappula-1735b9288/",
  },
  {
    title: "Competitive Programming Core Team Member",
    name: "Mani Yadla",
    src: "/img/team/Mani Yadla.jpg",
    instagram: "https://www.instagram.com/_mani_yadla/",
    github: "https://github.com/YadlaMani",
    linkedin: "https://www.linkedin.com/in/yadla-mani/",
  },
  {
    title: "Competitive Programming Core Team Member",
    name: "Devoju Siri",
    src: "/img/team/Devoju Siri.jpg",
    instagram: "https://www.instagram.com/im_siri6",
    github: "https://github.com/siridevoju",
    linkedin: "https://linkedin.com/in/siridevoju",
  },
  {
    title: "Competitive Programming Core Team Member",
    name: "Vemulakonda Sai Venkata Prabath",
    src: "/img/team/Vemulakonda Sai Venkata Prabath.jpg",
    instagram: "https://www.instagram.com/this_is_prabhath/",
    github: "https://github.com/Prabathvsv",
    linkedin: "https://www.linkedin.com/in/prabhath-vemulakonda-37b6a222a",
  },
  {
    name: "T Karthik Gupta",
    title: "IoT and Embedded Core Team Lead",
    src: "/img/team/T Karthik Gupta.png",
    instagram: "https://www.instagram.com/jame_smort/",
    linkedin: "http://linkedin.com/in/karthik-gupta-telukunta-884b3a26a",
  },
  {
    name: "Chindada Mahima Sharon",
    title: "IoT and Embedded Core Team Member",
    src: "/img/team/Chindada Mahima Sharon.jpg",
    instagram: "https://www.instagram.com/mahimasharxnn",
    github: "https://github.com/mahimasharonn",
    linkedin: "https://www.linkedin.com/in/mahima-sharon-chindada-b161aa319/",
  },
  {
    name: "Damuluri Sathvik",
    title: "IoT and Embedded Core Team Member",
    src: "/img/team/Damuluri Sathvik.jpg",
    instagram: "https://www.instagram.com/sathvikd09",
    github: "https://github.com/sathvikdamuluri",
    linkedin: "https://www.linkedin.com/in/sathvik-damuluri/",
  },
  {
    name: "Rendla Yashasri",
    title: "IoT and Embedded Core Team Member",
    src: "/img/team/Rendla Yashasri.jpg",
    instagram: "https://www.instagram.com/yashasri.04",
    github: "https://github.com/yashasri04",
    linkedin: "https://www.linkedin.com/in/yashasri-rendla-952362295/",
  },
  {
    name: "Ayush A. Shah",
    title: "Logistics Core Team Lead",
    src: "/img/team/Ayush A. Shah.jpg",
    instagram: "https://www.instagram.com/_ayushshah_07",
    github: "https://github.com/AyushShah-07",
    linkedin: "http://www.linkedin.com/in/ayush-shah-17646927b",
  },
  {
    name: "Dhruv Gupta",
    title: "Logistics Core Team Member",
    src: "/img/team/Dhruv Gupta.jpg",
    instagram: "https://www.instagram.com/dhruuu_txt",
    github: "https://github.com/dhruvvv07",
    linkedin: "http://www.linkedin.com/in/dhruvgupta007",
  },
  {
    name: "Kompally Amarthya",
    title: "Logistics Core Team Member",
    src: "/img/team/Kompally Amarthya.jpg",
    instagram: "https://www.instagram.com/amarthya_munna",
    github: "https://github.com/Amarthya076",
    linkedin:
      "https://www.linkedin.com/in/amarthya-kompally-a6ba2228b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  },
  {
    name: "Patalay Amrith",
    title: "Logistics Core Team Member",
    src: "/img/team/Patalay Amrith.jpeg",
    instagram: "https://www.instagram.com/P_amrith",
    github: "https://github.com/topics/login/patalayamrith",
    linkedin: "https://www.linkedin.com/in/amrith-patalay-92a498258",
  },
  {
    title: "Graphic Designer Core Team Lead",
    name: "U.Prajwal kumar",
    src: "/img/team/U.Prajwal kumar.jpg",
    instagram: "https://www.instagram.com/_prajwalkumarr_",
    github: "https://github.com/Prajwalkumarrr",
    linkedin: "http://www.linkedin.com/in/prajwalkumar-uppala",
  },
  {
    title: "Graphic Designer Core Team Member",
    name: "Akash Garine",
    src: "/img/team/Akash Garine.jpeg",
    instagram: "https://www.instagram.com/akash_garine",
    github: "https://github.com/akashgarine",
    linkedin: "https://www.linkedin.com/in/akashgarine",
  },
  {
    title: "Graphic Designer Core Team Member",
    name: "Vemulawada Omkar",
    src: "/img/team/Vemulawada Omkar.jpg",
    instagram: "https://www.instagram.com/Omkar_39356",
    github: "https://github.com/omkar393566",
    linkedin: "https://www.linkedin.com/in/omkar-vemulawada-691010301/",
  },
  {
    title: "Social Awareness Core Team",
    name: "Rishika Bussa",
    src: "/img/team/Rishika Bussa.jpg",
    instagram: "https://www.instagram.com/me_rishika_",
    github: "https://github.com/RishikaHub",
    linkedin:
      "https://www.linkedin.com/in/rishika-bussa?utm_source=share&utm_campaign=share_via&utm_content=profile",
  },
];

export const team2023: Profile[] = [
  {
    name: "Vijaya Mair",
    title: "Placement Co-ordinator and Mentor",
    src: "/img/team/vijaya_mair.jpg",
    linkedin: "https://www.linkedin.com/in/vijayamair/",
  },
  {
    name: "Seetharam Nagesh Appe",
    title: "Faculty Co-Ordinator",
    src: "/img/team/nagesh.jpeg",
    linkedin: "https://www.linkedin.com/in/seetharamnagesh-appe-4584281aa/",
  },
  {
    name: "Shubh A Chudasama",
    title: "GDSC Lead",
    src: "/img/team/Shubh A Chudasama.jpg",
    instagram: "https://www.instagram.com/c_shubh_/",
    github: "https://github.com/c-shubh/",
    linkedin: "https://www.linkedin.com/in/c-shubh/",
  },
  {
    name: "Deeskshitha Gona",
    title: "Management Lead and AI/ML Core Team Member",
    src: "/img/team/Deekshitha Gona.jpeg",
    instagram: "https://www.instagram.com/dexita_rao_gona/",
    linkedin: "https://www.linkedin.com/in/gona-deekshitha-543232235/",
  },
  {
    name: "Vikas Rushi",
    title: "Web Core Team Lead",
    src: "/img/team/Vikas Rushi.png",
    instagram: "https://www.instagram.com/vikas_rushi/",
    github: "https://github.com/0xVikasRushi/",
    linkedin: "https://www.linkedin.com/in/vikas-rushi/",
  },
  {
    title: "Web Core Team Member",
    name: "Pavan Manish Devulapally",
    src: "/img/team/Pavan Manish Devulapally.jpg",
    instagram: "https://www.instagram.com/pavanmanish.d/",
    github: "github.com/pavanmanishd",
    linkedin: "https://www.linkedin.com/in/pavanmanishd",
  },
  {
    title: "Web Core Team Member",
    name: "Suraj Thammi",
    src: "/img/team/Suraj Thammi.png",
    instagram: "https://www.instagram.com/suraj__712",
    github: "https://github.com/suraj719",
    linkedin: "https://www.linkedin.com/in/surajthammi/",
  },
  {
    title: "Web Core Team Member",
    name: "Puli Revanth Pershad",
    src: "/img/team/Puli Revanth Pershad.png",
    instagram: "https://www.instagram.com/revanthpershad",
    github: "https://github.com/Revanth-Pershad",
    linkedin: "https://www.linkedin.com/in/revanth-pershad-217937245/",
  },
  {
    title: "Web Core Team Member",
    name: "G Nithish Reddy",
    src: "/img/team/G Nithish Reddy.png",
    instagram: "https://www.instagram.com/nithish_reddy27",
    github: "https://github.com/nithishreddy27",
    linkedin: "https://www.linkedin.com/in/nithish-reddy-5703a11ba",
  },
  {
    title: "Android Core Team Lead",
    name: "Hitesh Lalwani",
    src: "/img/team/Hitesh Lalwani.jpg",
    github: "https://github.com/xobe19",
    linkedin: "https://www.linkedin.com/in/hiteshlwni/",
  },
  {
    title: "Android Core Team Member",
    name: "Aryan Shivva",
    src: "/img/team/Aryan Shivva.jpg",
    instagram: "https://www.instagram.com/aryanshivva",
    github: "https://github.com/AryanShivva",
    linkedin: "https://www.linkedin.com/in/aryan-shivva-839669256/",
  },
  {
    title: "Android Core Team Member",
    name: "Umang Darak",
    src: "/img/team/Umang Darak.png",
    instagram: "https://www.instagram.com/umang_darak",
    github: "https://github.com/umangdarak/TripPlanner",
    linkedin: "https://www.linkedin.com/in/umang-darak-14064025a",
  },
  {
    title: "Android Core Team Member",
    name: "Shaik Taj Baba",
    src: "/img/team/Shaik Taj Baba.png",
    instagram: "https://www.instagram.com/tajbaba999",
    github: "https://github.com/tajbaba999",
    linkedin: "https://www.linkedin.com/in/taj-baba-profile/",
  },
  {
    title: "Android Core Team Member",
    name: "Abbaraju Sai Sri Alekhya",
    src: "/img/team/Abbaraju Sai Sri Alekhya.jpg",
    instagram: "https://www.instagram.com/__.its_alekhya.__",
    github: "https://github.com/Alekhya-Abbaraju",
    linkedin: "www.linkedin.com/in/alekhya-abbaraju-628599231",
  },
  {
    title: "AI/ML Core Team Lead",
    name: "Dasula Akshat Mohan",
    src: "/img/team/Dasula Akshat Mohan.png",
    instagram: "https://www.instagram.com/kamearirikachi_159",
    github: "https://github.com/AkshatMittu?tab=repositories",
    linkedin: "www.linkedin.com/in/akshat-mohan-5a361b212",
  },
  {
    title: "AI/ML Core Team Member",
    name: "M Lakshminarayana Rao",
    src: "/img/team/M Lakshminarayana Rao.jpg",
    instagram: "https://www.instagram.com/ln11211",
    github: "https://github.com/Ln11211",
    linkedin: "https://www.linkedin.com/in/lakshminarayana-malyala/",
  },
  {
    title: "AI/ML Core Team Member",
    name: "Nithin Kumar Reddy Vangala",
    src: "/img/team/Nithin Kumar Reddy Vangala.jpg",
    instagram: "https://www.instagram.com/nithin_kumar_reddie",
    github: "https://github.com/Nithinkumar-29",
    linkedin:
      "https://www.linkedin.com/in/nithin-kumar-reddy-vangala-021b77212",
  },
  {
    title: "AI/ML Core Team Member",
    name: "Sai Vishal",
    src: "/img/team/Sai Vishal.jpg",
    instagram: "https://www.instagram.com/vishal_.sai",
    github: "https://github.com/Vishal0129",
    linkedin: "https://www.linkedin.com/in/vishal-sai-7033a9271",
  },
  {
    title: "Cybersecurity Core Team Lead",
    name: "Samrath Reddy Yelapati",
    src: "/img/team/Samrath Reddy Yelapati.png",
    github: "https://github.com/samrathreddy",
    linkedin: "https://www.linkedin.com/in/samrath-reddy-74103824a",
  },
  {
    title: "Cybersecurity Core Team Member",
    name: "Ramavath Rajaram",
    src: "/img/team/Ramavath Rajaram.png",
    instagram: "https://www.instagram.com/rajaram._.ramavath",
    github: "https://github.com/rajaramramavath",
    linkedin: "https://in.linkedin.com/in/rajaram-ramavath-8807731a0",
  },
  {
    title: "Cybersecurity Core Team Member",
    name: "Abhishyant Reddy",
    src: "/img/team/Abhishyant Reddy.jpg",
    instagram: "https://www.instagram.com/abhi_reds",
    github: "https://github.com/AbhishyantReds",
    linkedin: "https://www.linkedin.com/in/abhishyant-reddy-a87b23287/",
  },
  {
    title: "Cybersecurity Core Team Member",
    name: "Yashwanth Chilaka",
    src: "/img/team/Yashwanth Chilaka.jpg",
    instagram: "https://www.instagram.com/yashwanth.30",
    github: "https://github.com/Yashwanth-13",
    linkedin: "www.linkedin.com/in/yashwanth-chilaka-834284253",
  },
  {
    title: "Cybersecurity Core Team Member",
    name: "Tanusree Reddy",
    src: "/img/team/Tanusree Reddy.jpg",
    instagram: "https://www.instagram.com/tanusree.reddyy",
    github: "https://github.com/tanusree13",
    linkedin: "https://www.linkedin.com/in/tanusree-reddy-a46b24287/",
  },
  {
    title: "Blockchain Core Team Lead",
    name: "Sirangi Sanjay",
    src: "/img/team/Sirangi Sanjay.jpg",
    instagram: "https://www.instagram.com/sanjay_salvatore_",
    github: "https://github.com/sanjay-sol",
    linkedin: "https://www.linkedin.com/in/sanjay-sirangi/",
  },
  {
    title: "Blockchain Core Team Member",
    name: "Chandolu Yasvanth Venkata Sai",
    src: "/img/team/Chandolu Yasvanth Venkata Sai.jpg",
    instagram: "https://www.instagram.com/yashwanth_1027",
    github: "https://github.com/0xYashwanth",
    linkedin: "https://www.linkedin.com/in/yashwanth-chandolu-3705a3231/",
  },
  {
    title: "Blockchain Core Team Member",
    name: "Vinay Ganta",
    src: "/img/team/Vinay Ganta.jpg",
    instagram: "https://www.instagram.com/_mellomanic",
    linkedin: "https://www.linkedin.com/in/vinayganta/",
  },
  {
    title: "Graphic Designer",
    name: "Kowluru Sai",
    src: "/img/team/Kowluru Sai.jpeg",
    instagram: "https://www.instagram.com/sai_kowluru",
    linkedin: "https://www.linkedin.com/in/kowluru-sai-522032261",
  },
  {
    title: "Graphic Designer",
    name: "Yalamanchili Venkata Sridhar",
    src: "/img/team/Yalamanchili Venkata Sridhar.jpg",
    instagram: "https://www.instagram.com/yvsridhar2",
    linkedin: "https://www.linkedin.com/in/yv-sridhar-137674230",
  },
  {
    title: "Graphic Designer",
    name: "Himavarshini Attili",
    src: "/img/team/Himavarshini Attili.jpg",
    instagram: "https://www.instagram.com/himavarshini.attili",
    linkedin: "www.linkedin.com/in/himavarshini-attili",
  },
  {
    title: "Strategies & Operations",
    name: "Bellamkonda Leela Rishik",
    src: "/img/team/Bellamkonda Leela Rishik.JPEG",
    instagram: "https://www.instagram.com/am_rishik",
    linkedin: "https://www.linkedin.com/in/leela-rishik-bellamkonda-2998a3235",
  },
  {
    title: "Strategies & Operations and Public Relations",
    name: "Harshith Madhavaram",
    src: "/img/team/Harshith Madhavaram.png",
    instagram: "https://www.instagram.com/madhavaram.harshith",
    linkedin: "www.linkedin.com/in/harshith-madhavaram-37433322b",
  },
  {
    title: "Strategies & Operations",
    name: "Rishika Bussa",
    src: "/img/team/Rishika Bussa.jpg",
    instagram: "https://www.instagram.com/me_rishika_",
    linkedin: "https://www.linkedin.com/in/rishika-bussa-690bb2252",
  },
  {
    title: "Corporate Outreach",
    name: "Sathvika",
    src: "/img/team/Sathvika.jpg",
    instagram: "https://www.instagram.com/sathvika_reddy_24",
    linkedin: "https://www.linkedin.com/in/sathvika-reddy-6a2006259",
  },
  {
    title: "Corporate Outreach",
    name: "Patalay Amrith",
    src: "/img/team/Patalay Amrith.jpg",
    instagram: "https://www.instagram.com/p__amrith",
    linkedin: "https://www.linkedin.com/in/amrith-patalay-92a498258",
  },
  {
    title: "Corporate Outreach",
    name: "Sheetal Gujar",
    src: "/img/team/Sheetal Gujar.jpeg",
    linkedin: "https://www.linkedin.com/in/sheetal-gujar/",
  },
  {
    title: "Public Relations",
    name: "G Sneha",
    src: "/img/team/G Sneha.jpg",
    instagram: "https://www.instagram.com/sneha_gopishetty",
    linkedin: "https://www.linkedin.com/in/sneha-gopishetty-21b32027a",
  },
];

export const team2021: Profile[] = [
  {
    name: "Vijaya Mair",
    title: "Placement Co-ordinator and Mentor",
    src: "/img/team/vijaya_mair.jpg",
    linkedin: "https://www.linkedin.com/in/vijayamair/",
  },
  {
    name: "Seetharam Nagesh Appe",
    title: "Faculty Co-Ordinator",
    src: "/img/team/nagesh.jpeg",
    linkedin: "https://www.linkedin.com/in/seetharamnagesh-appe-4584281aa/",
  },
  {
    name: "Srimanth Tenneti",
    title: "Community Lead & Machine Learning Lead",
    src: "/img/team/SrimanthTenneti.jpg",
    instagram: "https://www.instagram.com/srimanth_tenneti/",
    github: "https://github.com/srimanthtenneti",
    linkedin: "https://www.linkedin.com/in/srimanth-tenneti-662b7117b/",
  },

  {
    name: "Vaishnavi Tammali",
    title: "Corporate Outreach Lead",
    src: "/img/team/vaishnavi.jpeg",
    instagram: "https://instagram.com/yshna_we?utm_medium=copy_link",
    github: "https://github.com/VaishnaviTammali",
    linkedin: "https://www.linkedin.com/in/vaishnavi-tammali-9a14801b3",
  },
  {
    name: "P Renu",
    title: "Content Lead",
    src: "/img/team/renu.png",
    instagram: "https://www.instagram.com/Pinjaralarenu/",
    linkedin: "https://www.linkedin.com/mwlite/in/pinjarala-r-4926581a5",
  },
  {
    name: "Sirichandan Reddy",
    title: "Management Lead",
    src: "/img/team/sirichandanreddy.JPG",
    instagram: "https://www.instagram.com/sirichandan_reddy/",
    linkedin:
      "https://www.linkedin.com/in/sirichandan-reddy-beeravolu-257b031b5/",
  },
  {
    name: "Vedanvita Gudavalli",
    title: "Strategies and Outreach Lead",
    src: "/img/team/vedanvitagudavalli.jpg",
    instagram: "https://www.instagram.com/vedanvita_/",
    github: "https://github.com/Vedanvita",
    linkedin: "http://www.linkedin.com/in/vedanvita-gudavalli-bb58971a7",
  },
  {
    name: "S Preetham Reddy",
    title: "Student Relations Lead",
    src: "/img/team/PreethamReddy.jpg",
    github: "https://github.com/Preetham71",
    linkedin: "https://www.linkedin.com/in/preetham-r-755128129",
  },
  {
    name: "Jannaikode Yashwanth Kumar",
    title: "Strategies and Operations Lead",
    src: "/img/team/yashwanth.jpg",
    instagram: "https://instagram.com/yashwanth_24_12?utm_medium=copy_link",
    github: "https://github.com/Yashwanth-Kumar24",
    linkedin: "https://www.linkedin.com/in/yashwanthkj",
  },
  {
    name: "Annam DevikaLahari",
    title: "Women Empowerment Lead",
    src: "/img/team/lahari.jpeg",
    instagram: "https://www.instagram.com/_lahari09_/",
    github: "https://github.com/L09-c",
    linkedin: "https://www.linkedin.com/in/lahari-annam-76b0a9192",
  },
  {
    name: "Thushar KE",
    title: "Web Development Lead",
    src: "/img/team/thushar.jpg",
    instagram: "https://www.instagram.com/thusharke25/",
    github: "https://github.com/thusharke",
    linkedin: "https://www.linkedin.com/in/thushar-ke-b00ba51a0/",
  },
  {
    name: "Shaik Adil",
    title: "GCP Facilitator & Web development core team",
    src: "/img/team/adil.jpg",
    instagram: "https://www.instagram.com/_adilshaik/",
    github: "https://github.com/adilshaik",
    linkedin: "https://www.linkedin.com/in/adil-shaik-7497a01b1/",
  },
  {
    name: "Karthik Pavoor ",
    title: "Wed development core team",
    src: "/img/team/karthikpavoor.jpg",
    instagram: "https://www.instagram.com/k_a_r_t_h_i_k_01/",
    github: "https://github.com/karthikpavoor",
    linkedin: "https://www.linkedin.com/in/karthik-pavoor-73331b21a/",
  },
  {
    name: "Rishi Shreshtham",
    title: "Machine Learning core team",
    src: "/img/team/rishishrestham.jpeg",
    instagram: "https://www.instagram.com/rishi_shreshtham/",
    github: "https://github.com/fluire",
    linkedin: "http://www.linkedin.com/in/rishi-shrestham-98a6231a9",
  },
  {
    name: "Hari Sri Purna Vishnu Karthik",
    title: "Machine Learning core team",
    src: "/img/team/harikarthik.jpeg",
    instagram: "https://www.instagram.com/hks3npai/",
    github: "https://github.com/hksenpai",
    linkedin: "https://www.linkedin.com/in/hari-karthik-46477b1b3/",
  },
  {
    name: "S Abhinav",
    title: "Machine Learning core team",
    src: "/img/team/Abhinav.png",
    instagram: "https://www.instagram.com/abhinavsam_03/",
    github: "https://github.com/sabhinav3",
    linkedin: "https://www.linkedin.com/in/s-abhinav/",
  },
  {
    name: "Pisati Sai Charan Reddy",
    title: "Machine Learning core team",
    src: "/img/team/Pisati.JPG",
    instagram: "https://github.com/saicharanreddypisati",
    github: "https://github.com/Wolfenstein31",
    linkedin: "http://linkedin.com/in/pisati-sai-charan-reddy-a41596205",
  },
  {
    name: "Sandeep P",
    title: "Android Lead",
    src: "/img/team/sandeep.jpg",
    instagram: "https://instagram.com/sandeepo9o7",
    github: "https://github.com/sandeep-prabhakula",
    linkedin: "https://www.linkedin.com/in/sandeep-prabhakula-791769202",
  },
  {
    name: "Nimma Likhitha",
    title: "Android core team",
    src: "/img/team/LikhithaNimma.jpeg",
    instagram: "https://www.instagram.com/likhitha_n_reddy/",
    github: "https://github.com/likhithanimma",
    linkedin: "https://www.linkedin.com/in/likhithanimma/",
  },
];
